// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjnsesvcgjtrspxhhrvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqbnNlc3ZjZ2p0cnNweGhocnZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDA0MjAsImV4cCI6MjA1OTk3NjQyMH0.6k8ODpGYc7lJP-ntSYQ9CID6qpc2Cz4GFl_4pdGi8nE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);